### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/storage#5]
- Fix `eslint` issues/warnings
- Remove wrapIntoObservable and isPromise from the Readme and exports. They should be private.
- add .cache to gitignore
- In getValue, add protection and wrap it with try catch.

Please fix these issues, and I'll add the npm token to the CI.

**Comment by NetanelBasal** [comment]
@va-stefanek did you saw this issue?

**Comment by va-stefanek** [comment]
Sorry I didn't :(. I will do it today/tomorrow

**Comment by va-stefanek** [comment]
@NetanelBasal 
What you would like to do in case of catch error in getValue? Return default value and console.log an error?
  getValue(key: string, defaultValue = {}): T {
    try {
      const item = localStorage.getItem(key);
      return item ? JSON.parse(item) : defaultValue;
    } catch (error) {
      console.log(error);
      return defaultValue as T;
    }
  }
```

**Comment by NetanelBasal** [comment]
There is no need for console.error. The default value should be undefined

**Comment by va-stefanek** [comment]
Ok, I am thinking also about the `updateStorage` method. I will propose to change it that it will accept the key to the storage and 'patch' which might be slice of the storage. That you can update multiple value by ones.

BEFORE

AFTER

**Comment by NetanelBasal** [comment]
You're assuming that the value is always an object. That's not flexible.

**Comment by va-stefanek** [comment]
You mean patch or storageValue? Because I make patch an object to allow updating multiple values at once. Under the hood it's always converted to 'object'.

**Comment by NetanelBasal** [comment]
```ts
return {
          ...storageValue,
          ...patch,
        };
```

This will force me to merge the value, what if I want to override it. It's better to use a callback.

**Comment by NetanelBasal** [comment]
Yes

**Comment by va-stefanek** [comment]
Done
